const $=s=>document.querySelector(s);let photo='';
const GN24_GUIDE='https://news24.ai.kr/pages/reporter-guide/';
function base(params={}){const u=new URL('./',location.href);u.search='';u.hash='';Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));return u.toString()}
function selectedOrg(){return $('#organization')?.value||'acts'}
function targetUrl(id){if(selectedOrg()==='gn24'){const u=new URL(GN24_GUIDE);u.searchParams.set('m',id);return u.toString()}return base({m:id})}
function preview(){const n=$('#name').value.trim()||'받는 분';const h=$('#honor').value;$('#previewTo').textContent=`${n} ${h}께`;$('#previewMessage').textContent=$('#message').value.trim()||'개인 메시지가 여기에 표시됩니다.';const note=$('#orgNote');if(note)note.textContent=selectedOrg()==='gn24'?'GLOBAL NEWS24 기자 안내비서 뉴스나가 받는 분의 이름·호칭·사진·메시지로 개인 맞춤 안내를 시작합니다.':'ACTS 소개 이야기 앞에 개인 손편지가 붙습니다.'}
async function compress(file){const b=await createImageBitmap(file),s=180,k=Math.min(s/b.width,s/b.height),w=Math.round(b.width*k),h=Math.round(b.height*k),c=document.createElement('canvas');c.width=s;c.height=s;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,s,s);x.drawImage(b,(s-w)/2,(s-h)/2,w,h);b.close();return c.toDataURL('image/jpeg',.64)}
$('#photo').addEventListener('change',async e=>{if(!e.target.files[0])return;photo=await compress(e.target.files[0]);$('#previewPhoto').src=photo;$('#previewPhoto').hidden=false});$('#form').addEventListener('input',preview);$('#form').addEventListener('change',preview);
$('#form').addEventListener('submit',async e=>{e.preventDefault();if(!window.HandWizardStore?.configured()){alert('개인 링크 저장소 설정을 확인해 주세요.');return}const btn=e.submitter;btn.disabled=true;btn.textContent='저장 중…';try{const org=selectedOrg();const id=await window.HandWizardStore.save({name:$('#name').value.trim(),honor:$('#honor').value,message:$('#message').value.trim(),photo,organization:org,template:org==='gn24'?'newsna-reporter-guide':'acts-story',version:'1.1'});const u=targetUrl(id);$('#url').value=u;$('#open').href=u;$('#result').hidden=false;$('#status').textContent=org==='gn24'?'GLOBAL NEWS24 뉴스나 개인 초대 링크가 완성되었습니다.':'10자리 개인 링크가 완성되었습니다.';$('#result').scrollIntoView({behavior:'smooth'})}catch(err){console.error(err);alert('저장하지 못했습니다. Supabase 연결을 확인해 주세요.')}finally{btn.disabled=false;btn.textContent='✨ 개인 링크 만들기'}});$('#copy').addEventListener('click',async()=>{await navigator.clipboard.writeText($('#url').value);$('#status').textContent='복사했습니다. 카카오톡에 붙여 넣어 보내세요.'});preview();
