const letters=[
{code:'KMT-W01-PERSONAL',org:'KMT',title:'계명태권도 학부모 개인 웹 편지',desc:'원생 이름·사진을 넣어 학부모에게 보내는 개인 맞춤형 웹 편지.',status:'live',statusLabel:'운영 가능',type:['개인편','학부모','계명태권도'],open:'../?m=10자리ID',edit:'https://github.com/jeonseongkweon-cloud/hand-wizard/edit/main/src/index.html'},
{code:'KMT-W01-COMMON',org:'KMT',title:'계명태권도 학부모 공통 웹 편지',desc:'모든 학부모에게 공통으로 전달할 수 있는 계명태권도 성장 이야기.',status:'live',statusLabel:'운영 가능',type:['공통편','학부모','계명태권도'],open:'../?mode=story01',edit:'https://github.com/jeonseongkweon-cloud/hand-wizard/edit/main/src/story/index.html'},
{code:'KMT-W02',org:'KMT',title:'계명태권도 × GLOBAL SPARK 학부모 웹 편지',desc:'계명태권도 학부모에게 GLOBAL SPARK의 취지와 참여를 소개하는 전용 편지.',status:'live',statusLabel:'운영 가능',type:['SPARK','학부모','소개'],open:'../spark/p01/',edit:'https://github.com/jeonseongkweon-cloud/hand-wizard/edit/main/src/spark/p01/index.html'},
{code:'ACTS-W01',org:'ACTS',title:'ACTS 선교연합 소개 웹 편지',desc:'ACTS를 만든 이유와 무도·교육·선교를 연결하는 비전을 전하는 웹 편지.',status:'live',statusLabel:'운영 가능',type:['ACTS','선교','소개'],open:'../acts/',edit:'https://github.com/jeonseongkweon-cloud/hand-wizard/edit/main/acts/index.html'},
{code:'SPARK-W01-v1.0',org:'SPARK',title:'GLOBAL SPARK 공용 웹 편지 · 작은 불꽃',desc:'과거 원본을 SHA 그대로 복원한 GLOBAL SPARK 공용 소개 웹 편지.',status:'archive',statusLabel:'복원 보관본',type:['GLOBAL SPARK','공용','복원본'],open:'../../archive/web-letters/SPARK-W01-v1.0/spark-magic.html',edit:'https://github.com/jeonseongkweon-cloud/hand-wizard/blob/main/archive/web-letters/SPARK-W01-v1.0/spark-magic.html'},
{code:'SPARK-W02',org:'SPARK',title:'GLOBAL SPARK 기관장 초청 웹 손편지',desc:'원장·관장·기관 운영자에게 GLOBAL SPARK와 성장기지를 소개하고 참여로 연결하는 공식 웹 손편지.',status:'live',statusLabel:'운영 가능',type:['GLOBAL SPARK','기관장','성장기지','초청'],open:'https://ipma1822-png.github.io/global-spark/web-letter/spark-w02/',edit:'https://github.com/ipma1822-png/global-spark/edit/main/web-letter/spark-w02/index.html'},
{code:'KMT-W01-ARCHIVE',org:'KMT',title:'계명태권도 개인편 원본 아카이브',desc:'과거 완성 시점의 개인 학부모 웹 편지를 원본 그대로 보관한 복원본.',status:'archive',statusLabel:'복원 보관본',type:['계명태권도','개인편','복원본'],open:'../../archive/web-letters/KMT-W01-PERSONAL/index.html',edit:'https://github.com/jeonseongkweon-cloud/hand-wizard/tree/main/archive/web-letters/KMT-W01-PERSONAL'},
{code:'KMT-W02-ARCHIVE',org:'KMT',title:'SPARK 학부모 P01 원본 아카이브',desc:'과거 SPARK 학부모 전용 페이지의 원본 보존본.',status:'archive',statusLabel:'복원 보관본',type:['SPARK','학부모','복원본'],open:'../../archive/web-letters/KMT-W02-SPARK-P01/index.html',edit:'https://github.com/jeonseongkweon-cloud/hand-wizard/tree/main/archive/web-letters/KMT-W02-SPARK-P01'},
{code:'ACTS-W01-ARCHIVE',org:'ACTS',title:'ACTS 웹 편지 원본 아카이브',desc:'ACTS 소개 웹 편지의 과거 원본 소스를 독립 보존한 버전.',status:'archive',statusLabel:'복원 보관본',type:['ACTS','복원본','보관'],open:'../../archive/web-letters/ACTS-W01/index.html',edit:'https://github.com/jeonseongkweon-cloud/hand-wizard/tree/main/archive/web-letters/ACTS-W01'},
{code:'IDP-W01',org:'IDP',title:'국제드론순찰대 웹 편지',desc:'카카오 공유 이미지와 관련 홍보 자산은 확인됨. 독립 웹 편지 원본은 추가 복원 조사 중.',status:'research',statusLabel:'조사 중',type:['드론순찰대','공익','후보'],open:'../../archive/web-letters/IDP-W01/',edit:'https://github.com/jeonseongkweon-cloud/hand-wizard/tree/main/archive/web-letters/IDP-W01'},
{code:'WTKF-W01',org:'OTHER',title:'태권검도 웹 편지',desc:'태권검도 홍보·창시자·수상·심벌 자산을 바탕으로 독립 웹 편지 원본을 추적 중.',status:'research',statusLabel:'조사 중',type:['태권검도','무도','후보'],open:'../../archive/web-letters/WTKF-W01/',edit:'https://github.com/jeonseongkweon-cloud/hand-wizard/tree/main/archive/web-letters/WTKF-W01'},
{code:'IPMA-W01',org:'OTHER',title:'IPMA 웹 편지',desc:'IPMA 공식 소개 및 공유 자료를 확인했으며 독립 웹 편지 여부를 추가 조사 중.',status:'research',statusLabel:'조사 중',type:['IPMA','국제네트워크','후보'],open:'../../archive/web-letters/IPMA-W01/',edit:'https://github.com/jeonseongkweon-cloud/hand-wizard/tree/main/archive/web-letters/IPMA-W01'},
{code:'GN24-W01',org:'OTHER',title:'Global News24 웹 편지 후보',desc:'기사 공유 페이지는 별도 공유 인프라로 분류. 독립 소개·초대형 웹 편지는 추가 조사 중.',status:'research',statusLabel:'조사 중',type:['Global News24','언론','후보'],open:'../../archive/web-letters/GN24-W01/',edit:'https://github.com/jeonseongkweon-cloud/hand-wizard/tree/main/archive/web-letters/GN24-W01'},
{code:'PUBLISHING-W01',org:'OTHER',title:'IPMA Publishing 웹 편지 후보',desc:'도서 공유 미리보기 페이지는 확인됨. 출판사 자체 소개 웹 편지는 추가 조사 중.',status:'research',statusLabel:'조사 중',type:['IPMA Publishing','출판','후보'],open:'../../archive/web-letters/PUBLISHING-W01/',edit:'https://github.com/jeonseongkweon-cloud/hand-wizard/tree/main/archive/web-letters/PUBLISHING-W01'}
];
const grid=document.getElementById('letterGrid');const search=document.getElementById('searchInput');const filters=document.getElementById('filters');const resultText=document.getElementById('resultText');let filter='all';
function escapeHtml(s){return String(s).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));}
function render(){const q=search.value.trim().toLowerCase();const rows=letters.filter(x=>(filter==='all'||x.org===filter)&&(!q||[x.code,x.title,x.desc,...x.type].join(' ').toLowerCase().includes(q)));grid.innerHTML=rows.length?rows.map(x=>`<article class="letter-card"><div class="card-top"><span class="code">${escapeHtml(x.code)}</span><span class="badge ${x.status}">${escapeHtml(x.statusLabel)}</span></div><h3>${escapeHtml(x.title)}</h3><p class="desc">${escapeHtml(x.desc)}</p><div class="meta">${x.type.map(t=>`<span>${escapeHtml(t)}</span>`).join('')}</div><div class="actions"><a class="open" href="${escapeHtml(x.open)}" target="_blank" rel="noopener">보기</a><button type="button" data-copy="${escapeHtml(x.open)}">링크 복사</button><a href="${escapeHtml(x.edit)}" target="_blank" rel="noopener">수정 위치</a><a href="${escapeHtml(x.edit)}" target="_blank" rel="noopener">GitHub 원본</a></div></article>`).join(''):'<div class="empty">조건에 맞는 웹 편지가 없습니다.</div>';resultText.textContent=`${rows.length}개 표시 중`;grid.querySelectorAll('[data-copy]').forEach(btn=>btn.addEventListener('click',()=>copyLink(btn)));}
async function copyLink(btn){const raw=btn.dataset.copy;const url=new URL(raw,location.href).href;try{await navigator.clipboard.writeText(url);const old=btn.textContent;btn.textContent='복사 완료';setTimeout(()=>btn.textContent=old,1200);}catch{prompt('아래 주소를 복사하세요.',url);}}
filters.addEventListener('click',e=>{const b=e.target.closest('button[data-filter]');if(!b)return;filter=b.dataset.filter;filters.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render();});search.addEventListener('input',render);
document.getElementById('totalCount').textContent=letters.length;document.getElementById('liveCount').textContent=letters.filter(x=>x.status==='live').length;document.getElementById('archiveCount').textContent=letters.filter(x=>x.status==='archive').length;document.getElementById('orgCount').textContent=new Set(letters.map(x=>x.org)).size;render();